//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/account.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen account

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_account_alternate_contact` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AlternateContactTfModel {
    pub alternate_contact_type: String,
    pub name: String,
    pub email_address: String,
    pub phone_number: String,
    pub title: String,
}
