//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/acmpca.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen acmpca

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_acmpca_certificate_authority` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CertificateAuthorityTfModel {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub key_storage_security_standard: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub certificate: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub certificate_chain: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub policy: Option<String>,
    #[serde(default)]
    pub tags: HashMap<String, String>,
}

/// Auto-generated TF-shaped projection of the `aws_acmpca_certificate` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CertificateTfModel {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    pub certificate_authority_arn: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub certificate: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub certificate_chain: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_acmpca_certificate_authority_certificate` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CertificateAuthorityCertificateTfModel {
    pub certificate_authority_arn: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub certificate: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub certificate_chain: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_acmpca_permission` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PermissionTfModel {
    pub certificate_authority_arn: String,
    pub principal: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source_account: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_acmpca_policy` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PolicyTfModel {
    pub resource_arn: String,
    pub policy: String,
}
