//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/amp.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen amp

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_prometheus_workspace` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkspaceTfModel {
    pub id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub alias: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prometheus_endpoint: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(default)]
    pub tags: HashMap<String, String>,
}
