//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/apigatewayv2.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen apigatewayv2

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_apigatewayv2_api` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApiTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub api_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub protocol_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub route_selection_expression: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub api_endpoint: Option<String>,
    #[serde(default)]
    pub tags: HashMap<String, String>,
}
