//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/apigateway.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen apigateway

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_api_gateway_rest_api` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RestApiTfModel {
    pub id: String,
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub api_key_source: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub policy: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub root_resource_id: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_api_gateway_resource` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApiGatewayResourceTfModel {
    pub id: String,
    pub rest_api_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub path_part: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_api_gateway_method` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApiGatewayMethodTfModel {
    pub rest_api_id: String,
    pub resource_id: String,
    pub http_method: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub authorization: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub authorizer_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub operation_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub request_validator_id: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_api_gateway_stage` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApiGatewayStageTfModel {
    pub rest_api_id: String,
    pub stage_name: String,
    pub deployment_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cache_cluster_size: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub documentation_version: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_api_gateway_deployment` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApiGatewayDeploymentTfModel {
    pub id: String,
    pub rest_api_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stage_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stage_description: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_api_gateway_api_key` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApiKeyTfModel {
    pub id: String,
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}
