//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/appflow.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen appflow

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_appflow_flow` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FlowTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub kms_arn: Option<String>,
    #[serde(default)]
    pub tags: HashMap<String, String>,
}
