//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/appfabric.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen appfabric

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_appfabric_app_bundle` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppBundleTfModel {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer_managed_key_arn: Option<String>,
    #[serde(default)]
    pub tags: HashMap<String, String>,
}
