//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/applicationautoscaling.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen applicationautoscaling

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_appautoscaling_target` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScalableTargetTfModel {
    pub service_namespace: String,
    pub resource_id: String,
    pub scalable_dimension: String,
    #[serde(default = "default_scalable_target_min_capacity")]
    pub min_capacity: i64,
    #[serde(default = "default_scalable_target_max_capacity")]
    pub max_capacity: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub role_arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
}

fn default_scalable_target_min_capacity() -> i64 {
    0i64
}

fn default_scalable_target_max_capacity() -> i64 {
    0i64
}

/// Auto-generated TF-shaped projection of the `aws_appautoscaling_policy` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScalingPolicyTfModel {
    pub name: String,
    pub service_namespace: String,
    pub resource_id: String,
    pub scalable_dimension: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub policy_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
}
