//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/applicationcostprofiler.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen applicationcostprofiler

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_applicationcostprofiler_report_definition` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReportDefinitionTfModel {
    pub report_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub format: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub report_description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub report_frequency: Option<String>,
}
