//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/appmesh.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen appmesh

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_appmesh_mesh` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MeshTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mesh_owner: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resource_owner: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created_date: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_updated_date: Option<String>,
    #[serde(default)]
    pub tags: HashMap<String, String>,
}

/// Auto-generated TF-shaped projection of the `aws_appmesh_virtual_node` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VirtualNodeTfModel {
    pub name: String,
    pub mesh_name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mesh_owner: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resource_owner: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created_date: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_updated_date: Option<String>,
    #[serde(default)]
    pub tags: HashMap<String, String>,
}

/// Auto-generated TF-shaped projection of the `aws_appmesh_virtual_service` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VirtualServiceTfModel {
    pub name: String,
    pub mesh_name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mesh_owner: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resource_owner: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created_date: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_updated_date: Option<String>,
    #[serde(default)]
    pub tags: HashMap<String, String>,
}
