//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/apprunner.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen apprunner

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_apprunner_service` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppRunnerServiceTfModel {
    pub service_name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service_url: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(default)]
    pub tags: HashMap<String, String>,
}
