//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/backup.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen backup

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_backup_vault` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VaultTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default)]
    pub tags: HashMap<String, String>,
}

/// Auto-generated TF-shaped projection of the `aws_backup_plan` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlanTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default)]
    pub tags: HashMap<String, String>,
}
