//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/budgets.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen budgets

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_budgets_budget` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BudgetTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub budget_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit_amount: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit_unit: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub time_unit: Option<String>,
}
