//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/chatbot.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen chatbot

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_chatbot_slack_channel_configuration` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SlackConfigTfModel {
    pub configuration_name: String,
    pub slack_team_id: String,
    pub slack_channel_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub slack_channel_name: Option<String>,
    pub iam_role_arn: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub chat_configuration_arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub logging_level: Option<String>,
    #[serde(default)]
    pub tags: HashMap<String, String>,
}

/// Auto-generated TF-shaped projection of the `aws_chatbot_microsoft_teams_channel_configuration` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TeamsConfigTfModel {
    pub configuration_name: String,
    pub team_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub team_name: Option<String>,
    pub tenant_id: String,
    pub channel_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub channel_name: Option<String>,
    pub iam_role_arn: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub chat_configuration_arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub logging_level: Option<String>,
    #[serde(default)]
    pub tags: HashMap<String, String>,
}
