//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/cloudfront.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen cloudfront

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_cloudfront_distribution` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DistributionTfModel {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub domain_name: Option<String>,
    #[serde(default = "default_distribution_enabled")]
    pub enabled: bool,
    #[serde(default)]
    pub tags: HashMap<String, String>,
}

fn default_distribution_enabled() -> bool {
    true
}
