//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/cloudhsmv2.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen cloudhsmv2

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_cloudhsm_v2_cluster` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ClusterTfModel {
    pub hsm_type: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cluster_id: Option<String>,
    #[serde(
        rename = "cluster_state",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub state: Option<String>,
    #[serde(
        rename = "security_group_id",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub security_group: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source_backup_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub vpc_id: Option<String>,
}
