//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/codecommit.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen codecommit

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_codecommit_repository` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RepositoryTfModel {
    pub repository_name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub repository_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub clone_url_http: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub clone_url_ssh: Option<String>,
}
