//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/codebuild.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen codebuild

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_codebuild_project` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProjectTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service_role: Option<String>,
}
