//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/codedeploy.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen codedeploy

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_codedeploy_app` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApplicationTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub application_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub compute_platform: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_codedeploy_deployment_group` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeploymentGroupTfModel {
    pub app_name: String,
    pub deployment_group_name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service_role_arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deployment_config_name: Option<String>,
}
