//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/cognitoidentity.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen cognitoidentity

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_cognito_identity_pool` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IdentityPoolTfModel {
    #[serde(rename = "id")]
    pub identity_pool_id: String,
    pub identity_pool_name: String,
    #[serde(default = "default_identity_pool_allow_unauthenticated_identities")]
    pub allow_unauthenticated_identities: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub developer_provider_name: Option<String>,
    #[serde(default)]
    pub tags: HashMap<String, String>,
}

fn default_identity_pool_allow_unauthenticated_identities() -> bool {
    false
}

/// Auto-generated TF-shaped projection of the `aws_cognito_identity_pool_roles_attachment` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CognitoIdentityPoolRolesAttachmentTfModel {
    pub identity_pool_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_cognito_identity_pool_provider_principal_tag` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CognitoIdentityPoolProviderPrincipalTagTfModel {
    pub identity_pool_id: String,
    pub identity_provider_name: String,
    #[serde(default = "default_cognito_identity_pool_provider_principal_tag_use_defaults")]
    pub use_defaults: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

fn default_cognito_identity_pool_provider_principal_tag_use_defaults() -> bool {
    true
}
