//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/dax.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen dax

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_dax_cluster` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DaxClusterTfModel {
    pub cluster_name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub node_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub iam_role_arn: Option<String>,
    #[serde(default)]
    pub replication_factor: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cluster_endpoint_encryption_type: Option<String>,
    #[serde(default)]
    pub tags: HashMap<String, String>,
}

/// Auto-generated TF-shaped projection of the `aws_dax_subnet_group` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DaxSubnetGroupTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub vpc_id: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_dax_parameter_group` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DaxParameterGroupTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}
