//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/directory.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen directory

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_directory_service_directory` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DirectoryTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub directory_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub short_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub size: Option<String>,
    #[serde(rename = "type", default, skip_serializing_if = "Option::is_none")]
    pub directory_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub alias: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub access_url: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stage: Option<String>,
    #[serde(default = "default_directory_enable_sso")]
    pub enable_sso: bool,
}

fn default_directory_enable_sso() -> bool {
    false
}
