//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/dynamodb.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen dynamodb

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_dynamodb_table` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TableTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    pub hash_key: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub range_key: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub billing_mode: Option<String>,
    #[serde(default = "default_table_read_capacity")]
    pub read_capacity: i64,
    #[serde(default = "default_table_write_capacity")]
    pub write_capacity: i64,
    #[serde(default = "default_table_stream_enabled")]
    pub stream_enabled: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stream_view_type: Option<String>,
}

fn default_table_read_capacity() -> i64 {
    5i64
}

fn default_table_write_capacity() -> i64 {
    5i64
}

fn default_table_stream_enabled() -> bool {
    false
}
