//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/ebs.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen ebs

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_ebs_volume` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VolumeTfModel {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub availability_zone: Option<String>,
    #[serde(default = "default_volume_size")]
    pub size: i64,
    #[serde(rename = "type", default, skip_serializing_if = "Option::is_none")]
    pub volume_type: Option<String>,
    #[serde(default = "default_volume_encrypted")]
    pub encrypted: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub kms_key_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub snapshot_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub volume_id: Option<String>,
    #[serde(default)]
    pub tags: HashMap<String, String>,
}

fn default_volume_size() -> i64 {
    8i64
}

fn default_volume_encrypted() -> bool {
    false
}

/// Auto-generated TF-shaped projection of the `aws_ebs_snapshot` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SnapshotTfModel {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub snapshot_id: Option<String>,
    #[serde(default = "default_snapshot_volume_size")]
    pub volume_size: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

fn default_snapshot_volume_size() -> i64 {
    8i64
}
