//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/ecr.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen ecr

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_ecr_repository` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RepositoryTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image_tag_mutability: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub repository_url: Option<String>,
    #[serde(default)]
    pub tags: HashMap<String, String>,
}
