//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/ecs.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen ecs

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_ecs_cluster` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ClusterTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_ecs_task_definition` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaskDefinitionTfModel {
    pub family: String,
    #[serde(default = "default_task_definition_revision")]
    pub revision: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub network_mode: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub task_role_arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub execution_role_arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cpu: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub memory: Option<String>,
}

fn default_task_definition_revision() -> i64 {
    1i64
}

/// Auto-generated TF-shaped projection of the `aws_ecs_service` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ServiceTfModel {
    pub name: String,
    pub task_definition: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cluster: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default = "default_service_desired_count")]
    pub desired_count: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub launch_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scheduling_strategy: Option<String>,
}

fn default_service_desired_count() -> i64 {
    1i64
}
