//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/elasticloadbalancing.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen elasticloadbalancing

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_elb` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ElbTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dns_name: Option<String>,
    #[serde(default = "default_elb_internal")]
    pub internal: bool,
    #[serde(default = "default_elb_cross_zone_load_balancing")]
    pub cross_zone_load_balancing: bool,
    #[serde(default = "default_elb_idle_timeout")]
    pub idle_timeout: i64,
    #[serde(default = "default_elb_connection_draining")]
    pub connection_draining: bool,
    #[serde(default)]
    pub tags: HashMap<String, String>,
}

fn default_elb_internal() -> bool {
    false
}

fn default_elb_cross_zone_load_balancing() -> bool {
    true
}

fn default_elb_idle_timeout() -> i64 {
    60i64
}

fn default_elb_connection_draining() -> bool {
    false
}
