//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/events.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen events

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_cloudwatch_event_bus` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventBusTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub policy: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub event_source_name: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_cloudwatch_event_rule` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventRuleTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub event_pattern: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub schedule_expression: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub event_bus_name: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_cloudwatch_event_target` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventTargetTfModel {
    pub rule: String,
    pub target_id: String,
    pub arn: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub input: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub input_path: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub event_bus_name: Option<String>,
}
