//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/firehose.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen firehose

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_kinesis_firehose_delivery_stream` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeliveryStreamTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub destination: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub version_id: Option<String>,
    #[serde(default)]
    pub tags: HashMap<String, String>,
}
