//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/fsx.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen fsx

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_fsx_lustre_file_system` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LustreFileSystemTfModel {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default = "default_lustre_file_system_storage_capacity")]
    pub storage_capacity: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub storage_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub kms_key_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dns_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub creation_time: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub lifecycle: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub lifecycle_status: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub owner_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub vpc_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deployment_type: Option<String>,
    #[serde(default = "default_lustre_file_system_copy_tags_to_backups")]
    pub copy_tags_to_backups: bool,
    #[serde(default = "default_lustre_file_system_automatic_backup_retention_days")]
    pub automatic_backup_retention_days: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub daily_automatic_backup_start_time: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub weekly_maintenance_start_time: Option<String>,
}

fn default_lustre_file_system_storage_capacity() -> i64 {
    1200i64
}

fn default_lustre_file_system_copy_tags_to_backups() -> bool {
    false
}

fn default_lustre_file_system_automatic_backup_retention_days() -> i64 {
    0i64
}

/// Auto-generated TF-shaped projection of the `aws_fsx_windows_file_system` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WindowsFileSystemTfModel {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default = "default_windows_file_system_storage_capacity")]
    pub storage_capacity: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub storage_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub kms_key_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dns_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub creation_time: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub lifecycle: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub lifecycle_status: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub owner_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub vpc_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deployment_type: Option<String>,
    #[serde(default = "default_windows_file_system_copy_tags_to_backups")]
    pub copy_tags_to_backups: bool,
    #[serde(default = "default_windows_file_system_automatic_backup_retention_days")]
    pub automatic_backup_retention_days: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub daily_automatic_backup_start_time: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub weekly_maintenance_start_time: Option<String>,
}

fn default_windows_file_system_storage_capacity() -> i64 {
    300i64
}

fn default_windows_file_system_copy_tags_to_backups() -> bool {
    false
}

fn default_windows_file_system_automatic_backup_retention_days() -> i64 {
    0i64
}
