//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/glacier.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen glacier

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_glacier_vault` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VaultTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub access_policy: Option<String>,
    #[serde(default)]
    pub tags: HashMap<String, String>,
}
