//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/ivs.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen ivs

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_ivs_channel` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChannelTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub latency_mode: Option<String>,
    #[serde(rename = "type", default, skip_serializing_if = "Option::is_none")]
    pub channel_type: Option<String>,
    #[serde(default = "default_channel_authorized")]
    pub authorized: bool,
    #[serde(default)]
    pub tags: HashMap<String, String>,
}

fn default_channel_authorized() -> bool {
    false
}
