//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/keyspaces.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen keyspaces

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_keyspaces_keyspace` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KeyspaceTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_keyspaces_table` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TableTfModel {
    pub keyspace_name: String,
    pub table_name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
}
