//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/kinesis.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen kinesis

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_kinesis_stream` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StreamTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default = "default_stream_shard_count")]
    pub shard_count: i64,
    #[serde(default = "default_stream_retention_period")]
    pub retention_period: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub encryption_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub kms_key_id: Option<String>,
    #[serde(default)]
    pub tags: HashMap<String, String>,
}

fn default_stream_shard_count() -> i64 {
    1i64
}

fn default_stream_retention_period() -> i64 {
    24i64
}

/// Auto-generated TF-shaped projection of the `aws_kinesis_resource_policy` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResourcePolicyTfModel {
    pub resource_arn: String,
    pub policy: String,
}

/// Auto-generated TF-shaped projection of the `aws_kinesis_stream_consumer` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StreamConsumerTfModel {
    pub name: String,
    pub stream_arn: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
}
