//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/kinesisanalyticsv2.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen kinesisanalyticsv2

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_kinesisanalyticsv2_application` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApplicationTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub runtime_environment: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service_execution_role: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default = "default_application_version_id")]
    pub version_id: i64,
    #[serde(default)]
    pub tags: HashMap<String, String>,
}

fn default_application_version_id() -> i64 {
    1i64
}
