//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/lakeformation.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen lakeformation

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_lakeformation_resource` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RegisteredResourceTfModel {
    #[serde(rename = "arn")]
    pub resource_arn: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub role_arn: Option<String>,
    #[serde(default = "default_registered_resource_use_service_linked_role")]
    pub use_service_linked_role: bool,
}

fn default_registered_resource_use_service_linked_role() -> bool {
    false
}

/// Auto-generated TF-shaped projection of the `aws_lakeformation_data_lake_settings` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DataLakeSettingsTfModel {
    #[serde(default = "default_data_lake_settings_allow_external_data_filtering")]
    pub allow_external_data_filtering: bool,
}

fn default_data_lake_settings_allow_external_data_filtering() -> bool {
    false
}
