//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/medialive.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen medialive

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_medialive_channel` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MediaLiveChannelTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub channel_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub channel_class: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub role_arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub log_level: Option<String>,
    #[serde(default)]
    pub tags: HashMap<String, String>,
}

/// Auto-generated TF-shaped projection of the `aws_medialive_input_security_group` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MediaLiveInputSecurityGroupTfModel {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub inputs: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
    #[serde(default)]
    pub tags: HashMap<String, String>,
}

/// Auto-generated TF-shaped projection of the `aws_medialive_multiplex` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MediaLiveMultiplexTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
    #[serde(default = "default_media_live_multiplex_start_multiplex")]
    pub start_multiplex: bool,
    #[serde(default)]
    pub tags: HashMap<String, String>,
}

fn default_media_live_multiplex_start_multiplex() -> bool {
    false
}

/// Auto-generated TF-shaped projection of the `aws_medialive_multiplex_program` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MediaLiveMultiplexProgramTfModel {
    pub program_name: String,
    pub multiplex_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_medialive_input` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MediaLiveInputTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub input_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub input_class: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub input_source_type: Option<String>,
    #[serde(rename = "type", default, skip_serializing_if = "Option::is_none")]
    pub input_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub role_arn: Option<String>,
    #[serde(default)]
    pub tags: HashMap<String, String>,
}
