//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/mq.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen mq

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_mq_broker` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BrokerTfModel {
    pub broker_name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub engine_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub engine_version: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub host_instance_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deployment_mode: Option<String>,
    #[serde(default = "default_broker_publicly_accessible")]
    pub publicly_accessible: bool,
    #[serde(default = "default_broker_auto_minor_version_upgrade")]
    pub auto_minor_version_upgrade: bool,
    #[serde(default)]
    pub tags: HashMap<String, String>,
}

fn default_broker_publicly_accessible() -> bool {
    false
}

fn default_broker_auto_minor_version_upgrade() -> bool {
    true
}

/// Auto-generated TF-shaped projection of the `aws_mq_configuration` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MqConfigurationTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub engine_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub engine_version: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub authentication_strategy: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub data: Option<String>,
    #[serde(default = "default_mq_configuration_latest_revision")]
    pub latest_revision: i64,
    #[serde(default)]
    pub tags: HashMap<String, String>,
}

fn default_mq_configuration_latest_revision() -> i64 {
    1i64
}
