//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/neptune.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen neptune

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_neptune_cluster` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DbClusterTfModel {
    pub cluster_identifier: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub engine: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub engine_version: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub engine_mode: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub master_username: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub database_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub neptune_subnet_group_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub neptune_cluster_parameter_group_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub kms_key_arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub endpoint: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reader_endpoint: Option<String>,
    #[serde(default = "default_db_cluster_storage_encrypted")]
    pub storage_encrypted: bool,
    #[serde(default = "default_db_cluster_copy_tags_to_snapshot")]
    pub copy_tags_to_snapshot: bool,
    #[serde(default = "default_db_cluster_deletion_protection")]
    pub deletion_protection: bool,
    #[serde(default = "default_db_cluster_backup_retention_period")]
    pub backup_retention_period: i64,
}

fn default_db_cluster_storage_encrypted() -> bool {
    false
}

fn default_db_cluster_copy_tags_to_snapshot() -> bool {
    false
}

fn default_db_cluster_deletion_protection() -> bool {
    false
}

fn default_db_cluster_backup_retention_period() -> i64 {
    1i64
}

/// Auto-generated TF-shaped projection of the `aws_neptune_cluster_instance` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DbInstanceTfModel {
    pub identifier: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub instance_class: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub engine: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub engine_version: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub neptune_subnet_group_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cluster_identifier: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub availability_zone: Option<String>,
    #[serde(default = "default_db_instance_auto_minor_version_upgrade")]
    pub auto_minor_version_upgrade: bool,
    #[serde(default = "default_db_instance_publicly_accessible")]
    pub publicly_accessible: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub neptune_parameter_group_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub endpoint: Option<String>,
    #[serde(default = "default_db_instance_storage_encrypted")]
    pub storage_encrypted: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub kms_key_arn: Option<String>,
}

fn default_db_instance_auto_minor_version_upgrade() -> bool {
    true
}

fn default_db_instance_publicly_accessible() -> bool {
    false
}

fn default_db_instance_storage_encrypted() -> bool {
    false
}

/// Auto-generated TF-shaped projection of the `aws_neptune_subnet_group` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DbSubnetGroupTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub vpc_id: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_neptune_parameter_group` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DbParameterGroupTfModel {
    pub name: String,
    pub family: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}
