//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/networkfirewall.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen networkfirewall

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_networkfirewall_firewall` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FirewallTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub firewall_policy_arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub vpc_id: Option<String>,
    #[serde(default = "default_firewall_delete_protection")]
    pub delete_protection: bool,
    #[serde(default = "default_firewall_subnet_change_protection")]
    pub subnet_change_protection: bool,
    #[serde(default = "default_firewall_firewall_policy_change_protection")]
    pub firewall_policy_change_protection: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

fn default_firewall_delete_protection() -> bool {
    false
}

fn default_firewall_subnet_change_protection() -> bool {
    false
}

fn default_firewall_firewall_policy_change_protection() -> bool {
    false
}

/// Auto-generated TF-shaped projection of the `aws_networkfirewall_firewall_policy` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FirewallPolicyTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_networkfirewall_rule_group` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RuleGroupTfModel {
    pub name: String,
    #[serde(rename = "type")]
    pub rule_group_type: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default = "default_rule_group_capacity")]
    pub capacity: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rules: Option<String>,
}

fn default_rule_group_capacity() -> i64 {
    100i64
}

/// Auto-generated TF-shaped projection of the `aws_networkfirewall_logging_configuration` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LoggingConfigurationTfModel {
    pub firewall_arn: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_networkfirewall_resource_policy` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NetworkFirewallResourcePolicyTfModel {
    pub resource_arn: String,
    pub policy: String,
}

/// Auto-generated TF-shaped projection of the `aws_networkfirewall_tls_inspection_configuration` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TlsInspectionConfigurationTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}
