//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/organizations.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen organizations

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_organizations_account` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AccountTfModel {
    pub name: String,
    pub email: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_organizations_organizational_unit` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrganizationalUnitTfModel {
    pub name: String,
    pub parent_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_organizations_policy` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrganizationsPolicyTfModel {
    pub name: String,
    pub content: String,
    #[serde(rename = "type", default, skip_serializing_if = "Option::is_none")]
    pub policy_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_organizations_organization` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrganizationsOrganizationTfModel {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub master_account_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub master_account_email: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub feature_set: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_organizations_delegated_administrator` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrganizationsDelegatedAdministratorTfModel {
    pub account_id: String,
    pub service_principal: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_organizations_policy_attachment` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrganizationsPolicyAttachmentTfModel {
    pub policy_id: String,
    pub target_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_organizations_resource_policy` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrganizationsResourcePolicyTfModel {
    pub content: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
}
