//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/osis.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen osis

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_osis_pipeline` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PipelineTfModel {
    pub pipeline_name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pipeline_arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pipeline_configuration_body: Option<String>,
    #[serde(default = "default_pipeline_min_units")]
    pub min_units: i64,
    #[serde(default = "default_pipeline_max_units")]
    pub max_units: i64,
    #[serde(default)]
    pub tags: HashMap<String, String>,
}

fn default_pipeline_min_units() -> i64 {
    1i64
}

fn default_pipeline_max_units() -> i64 {
    1i64
}
