//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/pinpoint.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen pinpoint

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_pinpoint_app` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PinpointAppTfModel {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub application_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub creation_date: Option<String>,
    #[serde(default)]
    pub tags: HashMap<String, String>,
}

/// Auto-generated TF-shaped projection of the `aws_pinpoint_email_channel` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmailChannelTfModel {
    pub application_id: String,
    #[serde(default = "default_email_channel_enabled")]
    pub enabled: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub from_address: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub identity: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub role_arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub configuration_set: Option<String>,
}

fn default_email_channel_enabled() -> bool {
    true
}
