//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/ram.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen ram

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_ram_resource_share` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResourceShareTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default = "default_resource_share_allow_external_principals")]
    pub allow_external_principals: bool,
    #[serde(default)]
    pub tags: HashMap<String, String>,
}

fn default_resource_share_allow_external_principals() -> bool {
    false
}
