//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/redshift.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen redshift

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_redshift_cluster` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RedshiftClusterTfModel {
    pub cluster_identifier: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub node_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub master_username: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub database_name: Option<String>,
    #[serde(default = "default_redshift_cluster_number_of_nodes")]
    pub number_of_nodes: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cluster_status: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cluster_version: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub availability_zone: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cluster_subnet_group_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub vpc_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub endpoint: Option<String>,
    #[serde(default = "default_redshift_cluster_port")]
    pub port: i64,
    #[serde(default = "default_redshift_cluster_encrypted")]
    pub encrypted: bool,
    #[serde(default = "default_redshift_cluster_publicly_accessible")]
    pub publicly_accessible: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub preferred_maintenance_window: Option<String>,
    #[serde(default = "default_redshift_cluster_automated_snapshot_retention_period")]
    pub automated_snapshot_retention_period: i64,
}

fn default_redshift_cluster_number_of_nodes() -> i64 {
    1i64
}

fn default_redshift_cluster_port() -> i64 {
    5439i64
}

fn default_redshift_cluster_encrypted() -> bool {
    false
}

fn default_redshift_cluster_publicly_accessible() -> bool {
    false
}

fn default_redshift_cluster_automated_snapshot_retention_period() -> i64 {
    1i64
}

/// Auto-generated TF-shaped projection of the `aws_redshift_subnet_group` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RedshiftSubnetGroupTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub vpc_id: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_redshift_authentication_profile` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RedshiftAuthenticationProfileTfModel {
    #[serde(rename = "authentication_profile_name")]
    pub name: String,
    #[serde(
        rename = "authentication_profile_content",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub content: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_redshift_cluster_iam_roles` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RedshiftClusterIamRolesTfModel {
    pub cluster_identifier: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub default_iam_role_arn: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_redshift_cluster_snapshot` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RedshiftClusterSnapshotTfModel {
    pub snapshot_identifier: String,
    pub cluster_identifier: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_redshift_event_subscription` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RedshiftEventSubscriptionTfModel {
    #[serde(rename = "name")]
    pub subscription_name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sns_topic_arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub severity: Option<String>,
    #[serde(default = "default_redshift_event_subscription_enabled")]
    pub enabled: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer_aws_id: Option<String>,
}

fn default_redshift_event_subscription_enabled() -> bool {
    true
}

/// Auto-generated TF-shaped projection of the `aws_redshift_hsm_client_certificate` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RedshiftHsmClientCertificateTfModel {
    #[serde(rename = "hsm_client_certificate_identifier")]
    pub identifier: String,
    #[serde(
        rename = "hsm_client_certificate_public_key",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub public_key: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_redshift_hsm_configuration` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RedshiftHsmConfigurationTfModel {
    #[serde(rename = "hsm_configuration_identifier")]
    pub identifier: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub hsm_ip_address: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub hsm_partition_name: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_redshift_logging` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RedshiftLoggingTfModel {
    pub cluster_identifier: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bucket_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub s3_key_prefix: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub log_destination_type: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_redshift_parameter_group` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RedshiftParameterGroupTfModel {
    pub name: String,
    pub family: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_redshift_partner` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RedshiftPartnerTfModel {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub account_id: Option<String>,
    pub cluster_identifier: String,
    pub database_name: String,
    pub partner_name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status_message: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_redshift_resource_policy` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RedshiftResourcePolicyTfModel {
    pub resource_arn: String,
    pub policy: String,
}

/// Auto-generated TF-shaped projection of the `aws_redshift_scheduled_action` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RedshiftScheduledActionTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub schedule: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub iam_role: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub start_time: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub end_time: Option<String>,
    #[serde(default = "default_redshift_scheduled_action_enable")]
    pub enable: bool,
}

fn default_redshift_scheduled_action_enable() -> bool {
    true
}

/// Auto-generated TF-shaped projection of the `aws_redshift_snapshot_copy` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RedshiftSnapshotCopyTfModel {
    pub cluster_identifier: String,
    pub destination_region: String,
    #[serde(default = "default_redshift_snapshot_copy_retention_period")]
    pub retention_period: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub snapshot_copy_grant_name: Option<String>,
}

fn default_redshift_snapshot_copy_retention_period() -> i64 {
    7i64
}

/// Auto-generated TF-shaped projection of the `aws_redshift_snapshot_copy_grant` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RedshiftSnapshotCopyGrantTfModel {
    #[serde(rename = "snapshot_copy_grant_name")]
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub kms_key_id: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_redshift_snapshot_schedule` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RedshiftSnapshotScheduleTfModel {
    #[serde(rename = "identifier")]
    pub schedule_identifier: String,
    #[serde(
        rename = "description",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub schedule_description: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_redshift_usage_limit` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RedshiftUsageLimitTfModel {
    pub cluster_identifier: String,
    pub feature_type: String,
    pub limit_type: String,
    pub amount: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub period: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub breach_action: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_redshift_data_share_authorization` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RedshiftDataShareAuthorizationTfModel {
    pub data_share_arn: String,
    pub consumer_identifier: String,
    #[serde(default = "default_redshift_data_share_authorization_allow_writes")]
    pub allow_writes: bool,
}

fn default_redshift_data_share_authorization_allow_writes() -> bool {
    false
}

/// Auto-generated TF-shaped projection of the `aws_redshift_data_share_consumer_association` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RedshiftDataShareConsumerAssociationTfModel {
    pub data_share_arn: String,
    #[serde(default = "default_redshift_data_share_consumer_association_allow_writes")]
    pub allow_writes: bool,
    #[serde(default = "default_redshift_data_share_consumer_association_associate_entire_account")]
    pub associate_entire_account: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub consumer_arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub consumer_region: Option<String>,
}

fn default_redshift_data_share_consumer_association_allow_writes() -> bool {
    false
}

fn default_redshift_data_share_consumer_association_associate_entire_account() -> bool {
    false
}

/// Auto-generated TF-shaped projection of the `aws_redshift_endpoint_access` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RedshiftEndpointAccessTfModel {
    pub endpoint_name: String,
    pub cluster_identifier: String,
    pub subnet_group_name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resource_owner: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_redshift_endpoint_authorization` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RedshiftEndpointAuthorizationTfModel {
    pub account: String,
    pub cluster_identifier: String,
    #[serde(default = "default_redshift_endpoint_authorization_force_delete")]
    pub force_delete: bool,
}

fn default_redshift_endpoint_authorization_force_delete() -> bool {
    false
}

/// Auto-generated TF-shaped projection of the `aws_redshift_integration` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RedshiftIntegrationTfModel {
    pub integration_name: String,
    pub source_arn: String,
    pub target_arn: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub kms_key_id: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_redshift_snapshot_schedule_association` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RedshiftSnapshotScheduleAssociationTfModel {
    pub cluster_identifier: String,
    pub schedule_identifier: String,
}
