//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/resiliencehub.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen resiliencehub

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_resiliencehub_resiliency_policy` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResiliencyPolicyTfModel {
    pub policy_name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub policy_arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub policy_description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub data_location_constraint: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tier: Option<String>,
}
