//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/rolesanywhere.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen rolesanywhere

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_rolesanywhere_profile` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProfileTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default = "default_profile_enabled")]
    pub enabled: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session_policy: Option<String>,
    #[serde(default)]
    pub tags: HashMap<String, String>,
}

fn default_profile_enabled() -> bool {
    true
}

/// Auto-generated TF-shaped projection of the `aws_rolesanywhere_trust_anchor` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TrustAnchorTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default = "default_trust_anchor_enabled")]
    pub enabled: bool,
    #[serde(default)]
    pub tags: HashMap<String, String>,
}

fn default_trust_anchor_enabled() -> bool {
    true
}
