//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/route53.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen route53

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_route53_zone` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HostedZoneTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub zone_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_route53_record` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResourceRecordSetTfModel {
    pub zone_id: String,
    pub name: String,
    #[serde(rename = "type")]
    pub record_type: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub set_identifier: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub health_check_id: Option<String>,
}
