//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/s3control.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen s3control

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_s3control_access_point` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AccessPointTfModel {
    pub name: String,
    pub bucket: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub account_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub alias: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub creation_date: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub network_origin: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub vpc_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub policy: Option<String>,
    #[serde(default)]
    pub block_public_acls: bool,
    #[serde(default)]
    pub ignore_public_acls: bool,
    #[serde(default)]
    pub block_public_policy: bool,
    #[serde(default)]
    pub restrict_public_buckets: bool,
}

/// Auto-generated TF-shaped projection of the `aws_s3control_bucket` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BucketTfModel {
    pub bucket: String,
    pub outpost_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub creation_date: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub policy: Option<String>,
    #[serde(default)]
    pub tags: HashMap<String, String>,
}
