//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/sagemaker.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen sagemaker

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_sagemaker_domain` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DomainTfModel {
    pub domain_name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub creation_time: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_modified_time: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub vpc_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub app_network_access_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub auth_mode: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub kms_key_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub home_efs_file_system_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_sagemaker_endpoint` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EndpointTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub endpoint_config_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub endpoint_status: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub creation_time: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_modified_time: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_sagemaker_endpoint_configuration` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EndpointConfigurationTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub creation_time: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_sagemaker_model` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModelTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub execution_role_arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub creation_time: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_sagemaker_notebook_instance` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NotebookInstanceTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub instance_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub role_arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub creation_time: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_modified_time: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub direct_internet_access: Option<String>,
    #[serde(default = "default_notebook_instance_volume_size")]
    pub volume_size: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub root_access: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notebook_instance_status: Option<String>,
}

fn default_notebook_instance_volume_size() -> i64 {
    5i64
}
