//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/scheduler.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen scheduler

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_scheduler_schedule_group` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScheduleGroupTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_scheduler_schedule` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScheduleTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub group_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub schedule_expression: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
}
