//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/servicequotas.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen servicequotas

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_servicequotas_service_quota` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ServiceQuotaTfModel {
    pub service_code: String,
    pub quota_code: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub quota_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub unit: Option<String>,
    #[serde(default = "default_service_quota_adjustable")]
    pub adjustable: bool,
    #[serde(default = "default_service_quota_global_quota")]
    pub global_quota: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

fn default_service_quota_adjustable() -> bool {
    false
}

fn default_service_quota_global_quota() -> bool {
    false
}
