//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/servicecatalogappregistry.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen servicecatalogappregistry

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_servicecatalogappregistry_application` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApplicationTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default)]
    pub tags: HashMap<String, String>,
}
