//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/sesv1.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen sesv1

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_ses_email_identity` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmailIdentityTfModel {
    pub email: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
}

/// Auto-generated TF-shaped projection of the `aws_ses_domain_identity` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DomainIdentityTfModel {
    pub domain: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub verification_token: Option<String>,
}
