//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/simpledbv2.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen simpledbv2

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_simpledb_domain` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DomainTfModel {
    pub name: String,
}
