//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/sqs.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen sqs

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_sqs_queue` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SqsQueueTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(
        rename = "visibility_timeout_seconds",
        default = "default_sqs_queue_visibility_timeout_seconds"
    )]
    pub visibility_timeout: u32,
    #[serde(default = "default_sqs_queue_delay_seconds")]
    pub delay_seconds: u32,
    #[serde(
        rename = "max_message_size",
        default = "default_sqs_queue_max_message_size"
    )]
    pub maximum_message_size: u32,
    #[serde(
        rename = "message_retention_seconds",
        default = "default_sqs_queue_message_retention_seconds"
    )]
    pub message_retention_period: u32,
    #[serde(default = "default_sqs_queue_receive_wait_time_seconds")]
    pub receive_wait_time_seconds: u32,
    #[serde(default = "default_sqs_queue_fifo_queue")]
    pub fifo_queue: bool,
    #[serde(default = "default_sqs_queue_content_based_deduplication")]
    pub content_based_deduplication: bool,
    #[serde(default)]
    pub tags: HashMap<String, String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub redrive_policy: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub policy: Option<String>,
}

fn default_sqs_queue_visibility_timeout_seconds() -> u32 {
    30u32
}

fn default_sqs_queue_delay_seconds() -> u32 {
    0u32
}

fn default_sqs_queue_max_message_size() -> u32 {
    262144u32
}

fn default_sqs_queue_message_retention_seconds() -> u32 {
    345600u32
}

fn default_sqs_queue_receive_wait_time_seconds() -> u32 {
    0u32
}

fn default_sqs_queue_fifo_queue() -> bool {
    false
}

fn default_sqs_queue_content_based_deduplication() -> bool {
    false
}
