//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/ssm.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen ssm

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_ssm_parameter` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ParameterTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    #[serde(default = "default_parameter_version")]
    pub version: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub data_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default)]
    pub tags: HashMap<String, String>,
}

fn default_parameter_version() -> i64 {
    1i64
}
