//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/ssoadmin.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen ssoadmin

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_ssoadmin_permission_set` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PermissionSetTfModel {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session_duration: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub relay_state: Option<String>,
    #[serde(default)]
    pub tags: HashMap<String, String>,
}

/// Auto-generated TF-shaped projection of the `aws_ssoadmin_account_assignment` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AccountAssignmentTfModel {
    pub permission_set_arn: String,
    pub principal_id: String,
    pub target_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub principal_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub target_type: Option<String>,
}
