//! Auto-generated by tf-converter-codegen. Do not edit manually.
//! Source: specs/transcribe.toml
//! Regenerate with: cargo run -p tf-converter-codegen -- gen transcribe

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

/// Auto-generated TF-shaped projection of the `aws_transcribe_vocabulary` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VocabularyTfModel {
    pub vocabulary_name: String,
    pub language_code: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub vocabulary_file_uri: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub failure_reason: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub download_uri: Option<String>,
    #[serde(default)]
    pub tags: HashMap<String, String>,
}

/// Auto-generated TF-shaped projection of the `aws_transcribe_language_model` resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LanguageModelTfModel {
    pub model_name: String,
    pub language_code: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub base_model_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub failure_reason: Option<String>,
    #[serde(default)]
    pub tags: HashMap<String, String>,
}
