[service]
name = "simpledbv2"
crate_name = "winterbaume_simpledbv2"
state_view_module = "views"

[[resource]]
type = "aws_simpledb_domain"
model = "DomainTfModel"
view = "SdbStateView"

[resource.modes]
mode = "model_only"

[[resource.field]]
hcl = "name"
view = "name"
type = "string"
required = true
