use chrono::{DateTime, Utc};

#[derive(Debug, Clone)]
pub struct Voice {
    pub id: String,
    pub name: String,
    pub gender: String,
    pub language_code: String,
    pub language_name: String,
    pub supported_engines: Vec<String>,
}

#[derive(Debug, Clone)]
pub struct Lexicon {
    pub name: String,
    pub content: String,
    pub language_code: String,
    pub lexemes_count: i32,
    pub size: i32,
    pub last_modified: DateTime<Utc>,
}

#[derive(Debug, Clone)]
pub struct SpeechSynthesisTask {
    pub task_id: String,
    pub task_status: String,
    pub output_uri: String,
    pub voice_id: String,
    pub text: String,
    pub creation_time: DateTime<Utc>,
    pub output_format: String,
    pub engine: String,
}

/// Static voice data — representative subset of real Polly voices.
pub const VOICES: &[(&str, &str, &str, &str, &str, &[&str])] = &[
    ("Aditi", "Aditi", "Female", "hi-IN", "Hindi", &["standard"]),
    (
        "Amy",
        "Amy",
        "Female",
        "en-GB",
        "British English",
        &["standard", "neural"],
    ),
    (
        "Aria",
        "Aria",
        "Female",
        "en-NZ",
        "New Zealand English",
        &["neural"],
    ),
    (
        "Astrid",
        "Astrid",
        "Female",
        "sv-SE",
        "Swedish",
        &["standard"],
    ),
    (
        "Brian",
        "Brian",
        "Male",
        "en-GB",
        "British English",
        &["standard", "neural"],
    ),
    (
        "Camila",
        "Camila",
        "Female",
        "pt-BR",
        "Brazilian Portuguese",
        &["standard", "neural"],
    ),
    (
        "Celine",
        "Celine",
        "Female",
        "fr-FR",
        "French",
        &["standard"],
    ),
    (
        "Chantal",
        "Chantal",
        "Female",
        "fr-CA",
        "Canadian French",
        &["standard"],
    ),
    (
        "Emma",
        "Emma",
        "Female",
        "en-GB",
        "British English",
        &["standard", "neural"],
    ),
    (
        "Gabrielle",
        "Gabrielle",
        "Female",
        "fr-CA",
        "Canadian French",
        &["neural"],
    ),
    ("Hans", "Hans", "Male", "de-DE", "German", &["standard"]),
    (
        "Ivy",
        "Ivy",
        "Female",
        "en-US",
        "US English",
        &["standard", "neural"],
    ),
    (
        "Joanna",
        "Joanna",
        "Female",
        "en-US",
        "US English",
        &["standard", "neural"],
    ),
    (
        "Joey",
        "Joey",
        "Male",
        "en-US",
        "US English",
        &["standard", "neural"],
    ),
    (
        "Justin",
        "Justin",
        "Male",
        "en-US",
        "US English",
        &["standard", "neural"],
    ),
    (
        "Kendra",
        "Kendra",
        "Female",
        "en-US",
        "US English",
        &["standard", "neural"],
    ),
    (
        "Kevin",
        "Kevin",
        "Male",
        "en-US",
        "US English",
        &["standard", "neural"],
    ),
    (
        "Kimberly",
        "Kimberly",
        "Female",
        "en-US",
        "US English",
        &["standard", "neural"],
    ),
    (
        "Lupe",
        "Lupe",
        "Female",
        "es-US",
        "US Spanish",
        &["standard", "neural"],
    ),
    (
        "Matthew",
        "Matthew",
        "Male",
        "en-US",
        "US English",
        &["standard", "neural"],
    ),
    (
        "Mizuki",
        "Mizuki",
        "Female",
        "ja-JP",
        "Japanese",
        &["standard"],
    ),
    (
        "Salli",
        "Salli",
        "Female",
        "en-US",
        "US English",
        &["standard", "neural"],
    ),
    (
        "Takumi",
        "Takumi",
        "Male",
        "ja-JP",
        "Japanese",
        &["standard", "neural"],
    ),
    (
        "Vicki",
        "Vicki",
        "Female",
        "de-DE",
        "German",
        &["standard", "neural"],
    ),
    (
        "Zhiyu",
        "Zhiyu",
        "Female",
        "cmn-CN",
        "Chinese Mandarin",
        &["standard", "neural"],
    ),
];
